# golangci-lint configuration for waza
# Custom configuration with practical settings

version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
    - staticcheck
  settings:
    errcheck:
      check-type-assertions: true
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports

run:
  tests: true
  modules-download-mode: readonly
