# golangci-lint configuration for waza
# Custom configuration with practical settings

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  misspell:
    locale: US
    extra-words:
      - typo: "analyses"
        correction: "analyses"

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
    - staticcheck

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
