// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/microsoft/waza/internal/execution (interfaces: GitResource)
//
// Generated by this command:
//
//	mockgen -package execution -destination execution_mocks_test.go . GitResource
//

// Package execution is a generated GoMock package.
package execution

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGitResource is a mock of GitResource interface.
type MockGitResource struct {
	ctrl     *gomock.Controller
	recorder *MockGitResourceMockRecorder
	isgomock struct{}
}

// MockGitResourceMockRecorder is the mock recorder for MockGitResource.
type MockGitResourceMockRecorder struct {
	mock *MockGitResource
}

// NewMockGitResource creates a new mock instance.
func NewMockGitResource(ctrl *gomock.Controller) *MockGitResource {
	mock := &MockGitResource{ctrl: ctrl}
	mock.recorder = &MockGitResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitResource) EXPECT() *MockGitResourceMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockGitResource) Cleanup(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockGitResourceMockRecorder) Cleanup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockGitResource)(nil).Cleanup), ctx)
}
